const KEY='my-day-v2-state';
const subjects=['Matemáticas','Lengua','Química','Biología','Inglés','Filosofía','Historia'];
const colors=['#e7a9bd','#b8a7d9','#9ccfd0','#a8c7ad','#e6c58b','#d7a7a0','#b8b0a8'];
const contexts=['Examen','Regla','Evento','Deporte','Calor','Lluvia','Mucho caminar','Normal'];
const tabs=[['home','✦','Inicio'],['wardrobe','👗','Ropa'],['calendar','📅','Calendario'],['routine','🎀','Rutina'],['schedule','🕰️','Horario'],['study','📚','Estudios']];
const today=new Date();
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{tab:'home',events:[],outfits:[],routines:[],schedule:{},tasks:[],notes:[],favOutfits:[],wardrobeWeek:{},settings:{name:'Cris',notifications:false},calYear:today.getFullYear(),calMonth:today.getMonth()};
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const iso=d=>{let x=new Date(d);return x.toISOString().slice(0,10)};
const fmt=d=>new Intl.DateTimeFormat('es-ES',{day:'numeric',month:'long',year:'numeric'}).format(new Date(d+'T12:00:00'));
function toast(t){const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),2400)}
function renderNav(){document.getElementById('nav').innerHTML=tabs.map(([id,ic,n])=>`<button class="nav-item ${state.tab===id?'active':''}" data-tab="${id}"><span>${ic}</span><small>${n}</small></button>`).join('');document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;save();render()})}
function render(){renderNav();const app=document.getElementById('app');app.innerHTML=views[state.tab]();bindCommon();}
function bindCommon(){document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>actions[b.dataset.action]?.(b.dataset.id));}
function views(){return {home:home,wardrobe:wardrobe,calendar:calendar,routine:routine,schedule:schedule,study:study}}
function home(){const pending=state.tasks.filter(x=>!x.done).length, events=state.events.filter(x=>x.date>=iso(today)).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,3), fav=state.outfits.filter(x=>state.favOutfits.includes(x.id));return `<div class="hero"><section class="card"><div class="eyebrow">MY DAY · ${today.toLocaleDateString('es-ES',{weekday:'long',day:'numeric',month:'long'})}</div><h1>Tu día, a tu manera.</h1><p class="quote">“Organiza. Planifica. Disfruta.”</p><div class="chips"><span class="chip">🎞️ editorial</span><span class="chip">🪩 disco chic</span><span class="chip">🌊 mediterránea</span><span class="chip">🐆 atrevida</span></div></section><section class="card sticker">⭐️<br><span class="small">little things, beautifully kept</span></section></div>
<div class="grid3"><div class="stat"><b>${pending}</b><small>tareas pendientes</small></div><div class="stat"><b>${events.length}</b><small>próximos eventos</small></div><div class="stat"><b>${fav.length}</b><small>outfits favoritos</small></div></div>
<div class="section-head"><h2>Próximo en tu vida</h2><button class="primary" data-action="newEvent">+ Evento</button></div><div class="list">${events.length?events.map(e=>`<div class="item"><span class="swatch" style="background:${e.color}"></span><div class="item-main"><strong>${esc(e.title)}</strong><div class="meta">${fmt(e.date)}${e.time?' · '+esc(e.time):''} · ${esc(e.category)}</div></div></div>`).join(''):`<div class="empty">Tu calendario está esperando acontecimientos. Qué dramático.</div>`}</div>
<div class="section-head"><h2>Favoritos ✦</h2><button class="ghost" data-action="goWardrobe">Ver ropa</button></div><div class="list">${fav.slice(0,3).map(o=>`<div class="item"><div class="item-main"><strong>👗 ${esc(o.text)}</strong><div class="meta">${esc(o.context||'Sin contexto')}</div></div></div>`).join('')||'<div class="empty">Guarda outfits que te encanten y aparecerán aquí.</div>'}</div>`}
function wardrobe(){const base=new Date();const monday=new Date(base);monday.setDate(base.getDate()-((base.getDay()+6)%7));const days=['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'];let proposals=state.outfits.filter(o=>!state.favOutfits.includes(o.id));if(!proposals.length) proposals=state.outfits;return `<div class="section-head"><div><div class="eyebrow">🎞️ WARDROBE</div><h2>Looks para esta semana</h2></div><button class="primary" data-action="newOutfit">+ Outfit</button></div><div class="week">${days.map((n,i)=>{let d=new Date(monday);d.setDate(monday.getDate()+i);let key=iso(d), items=state.outfits.filter(o=>o.date===key);return `<div><div class="weekday">${n}<br>${d.getDate()}</div><div class="outfit-day">${items.map(o=>`<div class="outfit"><button class="fav" data-action="toggleFav" data-id="${o.id}">${state.favOutfits.includes(o.id)?'♥':'♡'}</button> ${esc(o.text)}<div class="meta">${esc(o.context||'')}</div></div>`).join('')||'<div class="small">sin look</div>'}</div></div>`}).join('')}</div>
<div class="section-head"><h2>Propuestas ✨</h2><button class="ghost" data-action="propose">Generar</button></div><div id="proposalBox" class="card">${proposals.length?`<strong>Idea:</strong> ${esc(proposals[Math.floor(Math.random()*proposals.length)].text)}`:'Añade algunos outfits y My Day empezará a mezclarlos como una pequeña estilista digital.'}</div>
<div class="section-head"><h2>Historial</h2><span class="small">${state.outfits.length} looks guardados</span></div><div class="list">${state.outfits.slice().reverse().map(o=>`<div class="item"><div class="item-main"><strong>${esc(o.text)}</strong><div class="meta">${fmt(o.date)} · ${esc(o.context||'Normal')}</div></div><button class="fav" data-action="toggleFav" data-id="${o.id}">${state.favOutfits.includes(o.id)?'♥':'♡'}</button></div>`).join('')||'<div class="empty">Todavía no hay historial.</div>'}</div>`}
function calendar(){const y=state.calYear,m=state.calMonth,first=new Date(y,m,1),last=new Date(y,m+1,0),start=(first.getDay()+6)%7;let cells=[];for(let i=0;i<start;i++){const d=new Date(y,m,1-start+i);cells.push(dayCell(d,true))}for(let n=1;n<=last.getDate();n++)cells.push(dayCell(new Date(y,m,n),false));while(cells.length%7)cells.push(dayCell(new Date(y,m+1,cells.length-(start+last.getDate())+1),true));return `<div class="section-head"><div><div class="eyebrow">📅 CALENDAR · SIN FECHA FINAL</div><h2>Tu tiempo, en color</h2></div><button class="primary" data-action="newEvent">+ Evento</button></div><div class="card"><div class="toolbar" style="justify-content:center"><button class="ghost" data-action="prevMonth">‹</button><div class="month-title">${new Intl.DateTimeFormat('es-ES',{month:'long',year:'numeric'}).format(new Date(y,m,1))}</div><button class="ghost" data-action="nextMonth">›</button><button class="ghost" data-action="todayMonth">Hoy</button></div><div class="calendar" style="margin-top:14px">${['L','M','X','J','V','S','D'].map(x=>`<div class="cal-head">${x}</div>`).join('')}${cells.join('')}</div></div><div class="section-head"><h2>Tipos</h2></div><div class="chips">${['Examen','Cumpleaños','Colegio','Cita','Viaje','Entrega','Personal','Regla'].map((x,i)=>`<span class="chip"><span class="swatch" style="background:${colors[i%colors.length]}"></span>${x}</span>`).join('')}</div>`}
function dayCell(d,muted){const k=iso(d), ev=state.events.filter(e=>e.date===k);const isToday=k===iso(today);return `<div class="day ${muted?'muted':''} ${isToday?'today':''}" data-action="newEventForDate" data-id="${k}"><div class="daynum">${d.getDate()}</div>${ev.slice(0,3).map(e=>`<div class="eventbar" style="background:${e.color}"></div><div class="event-label">${esc(e.title)}</div>`).join('')}${ev.length>3?`<div class="small">+${ev.length-3}</div>`:''}</div>`}
function routine(){const todayTasks=state.routines.filter(r=>r.date===iso(today)||r.repeat);const done=todayTasks.filter(x=>x.done).length;return `<div class="section-head"><div><div class="eyebrow">🎀 ROUTINE</div><h2>Pequeños rituales</h2></div><button class="primary" data-action="newRoutine">+ Tarea</button></div><div class="card"><div class="grid3"><div class="stat"><b>${done}/${todayTasks.length}</b><small>completadas hoy</small></div><div class="stat"><b>${todayTasks.length-done}</b><small>pendientes</small></div><div class="stat"><b>☾</b><small>rutina nocturna</small></div></div></div><div class="section-head"><h2>Hoy</h2><button class="ghost" data-action="seedRoutines">Añadir rutina base</button></div><div class="list">${todayTasks.map(r=>`<label class="item"><input class="check" type="checkbox" ${r.done?'checked':''} data-routine="${r.id}"><div class="item-main"><strong>${esc(r.title)}</strong><div class="meta">${esc(r.slot)} ${r.time?'· '+esc(r.time):''}${r.repeat?' · recurrente':''}</div></div></label>`).join('')||'<div class="empty">Añade tu rutina de mañana, tarde o noche.</div>'}</div>`}
function schedule(){const times=['08:00','09:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00','17:00'];const days=['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'];return `<div class="section-head"><div><div class="eyebrow">🕰️ SCHEDULE</div><h2>Tu semana de clase</h2></div><button class="primary" data-action="editSchedule">+ Clase</button></div><div class="card" style="overflow:auto"><table class="table"><thead><tr><th>Hora</th>${days.map(d=>`<th>${d.slice(0,3)}</th>`).join('')}</tr></thead><tbody>${times.map(t=>`<tr><th>${t}</th>${days.map((d,i)=>{const key=i+'-'+t,s=state.schedule[key];return `<td data-schedule="${key}">${s?`<span class="subject" style="background:${colors[subjects.indexOf(s.subject)%colors.length]}">${esc(s.subject)}</span><div>${esc(s.teacher||'')}</div><div>${esc(s.room||'')}</div>`:'+'}</td>`}).join('')}</tr>`).join('')}</tbody></table></div>`}
function study(){const pending=state.tasks.filter(x=>!x.done);return `<div class="section-head"><div><div class="eyebrow">📚 STUDY CLUB</div><h2>Tu tarde, organizada</h2></div><button class="primary" data-action="newTask">+ Tarea</button></div><div class="chips">${subjects.map((s,i)=>`<span class="chip"><span class="swatch" style="background:${colors[i]}"></span>${s}</span>`).join('')}</div><div class="section-head"><h2>Agenda</h2><span class="small">${pending.length} pendientes</span></div><div class="list">${state.tasks.map(t=>`<label class="item"><input class="check" type="checkbox" ${t.done?'checked':''} data-task="${t.id}"><div class="item-main"><strong>${esc(t.title)}</strong><div class="meta">${esc(t.subject)} · ${t.date?fmt(t.date):'sin fecha'} · ${t.minutes||0} min · ${esc(t.priority||'normal')}</div></div></label>`).join('')||'<div class="empty">Tu tarde está sospechosamente vacía. Añade una tarea.</div>'}</div><div class="section-head"><h2>Apuntes 📸</h2><button class="primary" data-action="newNote">+ Foto</button></div><div class="photo-grid">${state.notes.map(n=>`<figure class="photo"><img src="${n.src}" alt="${esc(n.title)}"><figcaption>${esc(n.subject)} · ${esc(n.title)}</figcaption></figure>`).join('')||'<div class="empty" style="grid-column:1/-1">Sube fotos de tus apuntes y quedarán organizadas por asignatura.</div>'}</div>`}
function openModal(title,body){document.getElementById('modalRoot').innerHTML=`<div class="modal" id="modal"><div class="sheet"><div class="section-head"><h3>${title}</h3><button class="ghost" data-close>×</button></div>${body}</div></div>`;document.querySelector('[data-close]').onclick=()=>document.getElementById('modalRoot').innerHTML='';}
const actions={
newOutfit(){openModal('Nuevo outfit',`<form class="form" id="outfitForm"><label>Conjunto<input name="text" placeholder="Camiseta blanca + pantalón negro" required></label><label>Fecha<input type="date" name="date" value="${iso(today)}" required></label><label>Contexto<select name="context">${contexts.map(x=>`<option>${x}</option>`).join('')}</select></label><label>Notas<textarea name="notes" placeholder="Zapatos, bolso, accesorios..."></textarea></label><div class="form-actions"><button type="button" class="ghost" data-close>Cancelar</button><button class="primary">Guardar outfit</button></div></form>`);document.getElementById('outfitForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);state.outfits.push({id:crypto.randomUUID(),text:f.get('text'),date:f.get('date'),context:f.get('context'),notes:f.get('notes')});save();document.getElementById('modalRoot').innerHTML='';render();toast('Outfit guardado ✦')};},
toggleFav(id){state.favOutfits=state.favOutfits.includes(id)?state.favOutfits.filter(x=>x!==id):[...state.favOutfits,id];save();render();},
propose(){render();toast('Nueva propuesta generada ✨')},
newEvent(){actions.newEventForDate(iso(today))},newEventForDate(date){openModal('Nuevo evento',`<form class="form" id="eventForm"><label>Nombre<input name="title" placeholder="Examen de Biología" required></label><label>Fecha<input type="date" name="date" value="${date}" required></label><label>Hora<input type="time" name="time"></label><label>Categoría<select name="category">${['Examen','Cumpleaños','Colegio','Cita','Viaje','Entrega','Personal','Regla'].map(x=>`<option>${x}</option>`).join('')}</select></label><label>Color<select name="color">${colors.map(c=>`<option value="${c}">${c}</option>`).join('')}</select></label><label><input type="checkbox" name="repeat"> Repetir cada año</label><label>Recordatorio<select name="reminder"><option value="0">Sin recordatorio</option><option value="1440">1 día antes</option><option value="10080">1 semana antes</option></select></label><div class="form-actions"><button type="button" class="ghost" data-close>Cancelar</button><button class="primary">Guardar</button></div></form>`);document.getElementById('eventForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);state.events.push({id:crypto.randomUUID(),title:f.get('title'),date:f.get('date'),time:f.get('time'),category:f.get('category'),color:f.get('color'),repeat:f.has('repeat'),reminder:+f.get('reminder')});save();document.getElementById('modalRoot').innerHTML='';render();toast('Evento guardado 📅')};},
prevMonth(){state.calMonth--;if(state.calMonth<0){state.calMonth=11;state.calYear--}save();render()},nextMonth(){state.calMonth++;if(state.calMonth>11){state.calMonth=0;state.calYear++}save();render()},todayMonth(){state.calYear=today.getFullYear();state.calMonth=today.getMonth();save();render()},
newRoutine(){openModal('Nueva rutina',`<form class="form" id="routineForm"><label>Tarea<input name="title" placeholder="Skincare, preparar mochila..." required></label><label>Momento<select name="slot"><option>Mañana</option><option>Tarde</option><option>Noche</option></select></label><label>Hora<input type="time" name="time"></label><label><input type="checkbox" name="repeat" checked> Repetir cada día</label><div class="form-actions"><button type="button" class="ghost" data-close>Cancelar</button><button class="primary">Guardar</button></div></form>`);document.getElementById('routineForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);state.routines.push({id:crypto.randomUUID(),title:f.get('title'),slot:f.get('slot'),time:f.get('time'),repeat:f.has('repeat'),date:iso(today),done:false});save();document.getElementById('modalRoot').innerHTML='';render()};},
seedRoutines(){['Tender la cama','Skincare de mañana','Preparar mochila','Skincare de noche','Preparar outfit de mañana'].forEach((title,i)=>state.routines.push({id:crypto.randomUUID(),title,slot:i<3?'Mañana':'Noche',time:'',repeat:true,date:iso(today),done:false}));save();render();toast('Rutina base añadida 🎀')},
editSchedule(){openModal('Añadir clase',`<form class="form" id="scheduleForm"><label>Día<select name="day">${['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'].map((x,i)=>`<option value="${i}">${x}</option>`).join('')}</select></label><label>Hora<select name="time">${['08:00','09:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00','17:00'].map(x=>`<option>${x}</option>`).join('')}</select></label><label>Asignatura<select name="subject">${subjects.map(x=>`<option>${x}</option>`).join('')}</select></label><label>Profesor<input name="teacher"></label><label>Aula<input name="room"></label><div class="form-actions"><button type="button" class="ghost" data-close>Cancelar</button><button class="primary">Guardar</button></div></form>`);document.getElementById('scheduleForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);state.schedule[f.get('day')+'-'+f.get('time')]={subject:f.get('subject'),teacher:f.get('teacher'),room:f.get('room')};save();document.getElementById('modalRoot').innerHTML='';render()};},
newTask(){openModal('Nueva tarea de estudio',`<form class="form" id="taskForm"><label>Tarea<input name="title" placeholder="Repasar formulación" required></label><label>Asignatura<select name="subject">${subjects.map(x=>`<option>${x}</option>`).join('')}</select></label><label>Fecha<input type="date" name="date" value="${iso(today)}"></label><label>Tiempo estimado (min)<input type="number" name="minutes" value="45" min="5"></label><label>Prioridad<select name="priority"><option>alta</option><option selected>normal</option><option>baja</option></select></label><label>Recordatorio<input type="time" name="time"></label><div class="form-actions"><button type="button" class="ghost" data-close>Cancelar</button><button class="primary">Guardar tarea</button></div></form>`);document.getElementById('taskForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);state.tasks.push({id:crypto.randomUUID(),title:f.get('title'),subject:f.get('subject'),date:f.get('date'),minutes:+f.get('minutes'),priority:f.get('priority'),time:f.get('time'),done:false});save();document.getElementById('modalRoot').innerHTML='';render();toast('Tarea guardada 📚')};},
newNote(){openModal('Guardar apuntes',`<form class="form" id="noteForm"><label>Asignatura<select name="subject">${subjects.map(x=>`<option>${x}</option>`).join('')}</select></label><label>Título<input name="title" placeholder="Tema 1 · apuntes de clase"></label><label>Foto<input type="file" name="file" accept="image/*" required></label><div class="form-actions"><button type="button" class="ghost" data-close>Cancelar</button><button class="primary">Guardar foto</button></div></form>`);document.getElementById('noteForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),file=f.get('file');const reader=new FileReader();reader.onload=()=>{state.notes.push({id:crypto.randomUUID(),subject:f.get('subject'),title:f.get('title')||'Apuntes',src:reader.result});save();document.getElementById('modalRoot').innerHTML='';render();toast('Apunte guardado 📸')};reader.readAsDataURL(file)},},
goWardrobe(){state.tab='wardrobe';save();render()}
};
document.addEventListener('change',e=>{if(e.target.matches('[data-routine]')){const r=state.routines.find(x=>x.id===e.target.dataset.routine);if(r){r.done=e.target.checked;save();render()}}if(e.target.matches('[data-task]')){const t=state.tasks.find(x=>x.id===e.target.dataset.task);if(t){t.done=e.target.checked;save();render()}}});
document.addEventListener('click',e=>{const cell=e.target.closest('[data-schedule]');if(cell){const k=cell.dataset.schedule;if(state.schedule[k]){if(confirm('¿Eliminar esta clase?')){delete state.schedule[k];save();render()}}}const day=e.target.closest('.day[data-action="newEventForDate"]');if(day&&!e.target.closest('button')) actions.newEventForDate(day.dataset.id)});
document.getElementById('settingsBtn').onclick=()=>openModal('Ajustes de My Day',`<div class="form"><label>Nombre<input id="settingsName" value="${esc(state.settings.name)}"></label><label><input id="notif" type="checkbox" ${state.settings.notifications?'checked':''}> Permitir notificaciones del navegador</label><p class="small">Las notificaciones web dependen del navegador y de que la app esté instalada como PWA. GitHub Pages no puede ejecutar un servidor de push por sí solo.</p><div class="form-actions"><button class="primary" id="saveSettings">Guardar</button></div></div>`);setTimeout(()=>{document.getElementById('saveSettings').onclick=async()=>{state.settings.name=document.getElementById('settingsName').value;state.settings.notifications=document.getElementById('notif').checked;if(state.settings.notifications&&'Notification'in window){const p=await Notification.requestPermission();toast(p==='granted'?'Notificaciones permitidas 🔔':'Permiso de notificaciones no concedido')};save();document.getElementById('modalRoot').innerHTML='';render()}},0);
if('serviceWorker'in navigator) window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
render();
